version: 2
updates:
- package-ecosystem: bazel
  directories:
  - /bazel
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"

- package-ecosystem: cargo
  directories:
  - /rust
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"

- package-ecosystem: github-actions
  directories:
  - /
  - /gh-actions/bson
  - /gh-actions/cache/prime
  - /gh-actions/cache/restore
  - /gh-actions/docker/cache/prime
  - /gh-actions/docker/cache/restore
  - /gh-actions/docker/fetch
  - /gh-actions/docker/shas
  - /gh-actions/envoy/android/pre
  - /gh-actions/envoy/ci/env
  - /gh-actions/envoy/ci/request
  - /gh-actions/envoy/ios/post
  - /gh-actions/envoy/run/summary
  - /gh-actions/foreach
  - /gh-actions/github/artifact/download
  - /gh-actions/github/checkout
  - /gh-actions/github/command
  - /gh-actions/github/env/load
  - /gh-actions/github/env/save
  - /gh-actions/github/env/summary
  - /gh-actions/github/merge-commit
  - /gh-actions/github/pr
  - /gh-actions/github/run
  - /gh-actions/json/table
  - /gh-actions/upload/diff
  - /gh-actions/using/recurse
  - /gh-actions/using/steps
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"

- package-ecosystem: npm
  directories:
  - /gh-actions/appauth
  - /gh-actions/dispatch
  - /gh-actions/github/checks
  - /gh-actions/github/mutex
  - /gh-actions/github/script/run
  - /gh-actions/hashfiles
  - /gh-actions/jq
  - /gh-actions/retest
  - /gh-actions/torun
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"

- package-ecosystem: pip
  directories:
  - /bazel
  - /bazel/website
  - /ci
  - /gh-actions/gcp/setup
  - /py/deps
  - /py/deps/docformatter
  - /py/deps/flake8
  - /py/deps/mypy
  - /py/deps/pytest
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
