version: 2
updates:
- package-ecosystem: bazel
  directories:
  - /bazel
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"

- package-ecosystem: cargo
  directories:
  - /rust
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"

- package-ecosystem: github-actions
  directories:
  - /
  - /actions/bson
  - /actions/cache/prime
  - /actions/cache/restore
  - /actions/docker/cache/prime
  - /actions/docker/cache/restore
  - /actions/docker/fetch
  - /actions/docker/shas
  - /actions/envoy/android/pre
  - /actions/envoy/ci/env
  - /actions/envoy/ci/request
  - /actions/envoy/ios/post
  - /actions/envoy/run/summary
  - /actions/foreach
  - /actions/github/artifact/download
  - /actions/github/checkout
  - /actions/github/command
  - /actions/github/env/load
  - /actions/github/env/save
  - /actions/github/env/summary
  - /actions/github/merge-commit
  - /actions/github/pr
  - /actions/github/run
  - /actions/json/table
  - /actions/upload/diff
  - /actions/using/recurse
  - /actions/using/steps
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"

- package-ecosystem: npm
  directories:
  - /actions/appauth
  - /actions/dispatch
  - /actions/github/checks
  - /actions/github/mutex
  - /actions/github/script/run
  - /actions/hashfiles
  - /actions/jq
  - /actions/retest
  - /actions/torun
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"

- package-ecosystem: pip
  directories:
  - /bazel
  - /bazel/website
  - /ci
  - /actions/gcp/setup
  - /py/deps
  - /py/deps/docformatter
  - /py/deps/flake8
  - /py/deps/mypy
  - /py/deps/pytest
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
