[package]
name = "toolshed-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0.97"
as-any = "^0.3.2"
indexmap = { version = "^2.8.0", features = ["serde"] }
serde = { version = "^1.0.219", features = ["derive"] }
tokio = "1.49.0"

[dev-dependencies]
serial_test = "^3.3.1"
serde_json = "^1.0.149"

[lib]
name = "toolshed_core"
path = "src/lib.rs"
