name: Bazel CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}


jobs:
  request:
    runs-on: ubuntu-24.04
    outputs:
      run: ${{ steps.filter.outputs.run }}
    steps:
    - uses: envoyproxy/toolshed/actions/github/should-run@8bcc8dc6d3fc28d318e66e1121162cd8bc1d3197
      id: filter
      with:
        config: |
          paths:
          - BINS_VERSION.txt
          - bazel/**
          - .github/workflows/bazel.yml
          - .github/workflows/_bazel.yml

  test:
    needs: request
    if: >-
      always()
      && fromJSON(needs.request.outputs.run || 'false')
    uses: ./.github/workflows/_bazel.yml
    with:
      action: test
      bazel-args: >-
        --config=ci
        ${{ matrix.mode == 'bzlmod'
            && '--enable_bzlmod'
            || '' }}
      bazel-mode: ${{ matrix.mode }}
      bazel-path: bazel
      targets: >-
        //...
        //sysroot:sysroots
    strategy:
      fail-fast: false
      matrix:
        mode:
        - workspace
        - bzlmod

  build:
    permissions:
      contents: write
    needs: request
    if: >-
      always()
      && fromJSON(needs.request.outputs.run || 'false')
    uses: ./.github/workflows/_bazel.yml
    with:
      action: build
      artifacts: |
          compile/msan-llvm18.1.8-x86_64.tar.xz
          compile/tsan-llvm18.1.8-x86_64.tar.xz
          sysroot/sysroot-*.tar.xz
      bazel-args: >-
        --config=ci
        ${{ matrix.mode == 'bzlmod'
            && '--enable_bzlmod'
            || '' }}
      bazel-path: bazel
      bazel-mode: ${{ matrix.mode }}
      targets: >-
        //...
        //sysroot:sysroots
      upload: ${{ matrix.mode == 'workspace' }}
    strategy:
      fail-fast: false
      matrix:
        mode:
        - workspace
        - bzlmod

  test-gcc:
    needs: request
    if: >-
      always()
      && fromJSON(needs.request.outputs.run || 'false')
    uses: ./.github/workflows/_bazel.yml
    with:
      action: build
      bazel-args: >-
        --config=ci
        --config=gcc
        ${{ matrix.mode == 'bzlmod'
            && '--enable_bzlmod'
            || '' }}
      bazel-mode: ${{ matrix.mode }}-gcc
      bazel-path: bazel
      targets: >-
        //...
    strategy:
      fail-fast: false
      matrix:
        mode:
        - workspace
        - bzlmod

  test-macos:
    runs-on: macos-14
    needs: request
    if: >-
      always()
      && fromJSON(needs.request.outputs.run || 'false')
    strategy:
      fail-fast: false
      matrix:
        mode:
        - workspace
        - bzlmod
    steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Setup Bazel
      uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2  # v3
    - name: Bazel targets (build/${{ matrix.mode }}-macos)
      run: |
        exec bazel build \
          --config=ci \
          --config=macos \
          ${{ matrix.mode == 'bzlmod' && '--enable_bzlmod' || '' }} \
          //...
      working-directory: bazel

  status:
    runs-on: ubuntu-24.04
    if: >-
      always()
      && github.event_name == 'pull_request'
    name: Bazel
    needs:
    - request
    - test
    - build
    - test-gcc
    - test-macos
    steps:
    - run: |
        if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled"
            exit 1
        fi
        echo "All required jobs passed or were skipped"
