name: Bazel tests

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
    - main
  release:
    types:
    - published

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  should:
    runs-on: ubuntu-24.04
    if: github.event_name != 'release'
    outputs:
      run: ${{ steps.filter.outputs.run }}
    steps:
    - uses: envoyproxy/toolshed/gh-actions/github/should-run@c04bdf5c854da00a30144f3597967e73ca376f38
      id: filter
      with:
        config: |
          paths:
          - 'bazel/**'
          - '.github/workflows/bazel.yml'
          - '.github/workflows/_bazel.yml'

  test-workspace:
    if: >-
      always()
      && github.event_name != 'release'
      && fromJSON(needs.should.outputs.run || 'false')
    needs: should
    uses: ./.github/workflows/_bazel.yml
    permissions:
      contents: read
    with:
      mode: workspace
      enable-publishing: false

  test-bzlmod:
    if: >-
      always()
      && github.event_name != 'release'
      && fromJSON(needs.should.outputs.run || 'false')
    needs: should
    uses: ./.github/workflows/_bazel.yml
    permissions:
      contents: read
    with:
      mode: bzlmod
      enable-publishing: false

  build-and-publish:
    if: >-
      github.event_name == 'release'
      && startsWith(github.event.release.name, 'bins-')
    uses: ./.github/workflows/_bazel.yml
    permissions:
      contents: write
    with:
      mode: workspace
      enable-publishing: true

  status:
    runs-on: ubuntu-24.04
    if: >-
      always()
      && github.event_name == 'pull_request'
    name: Bazel
    needs:
    - should
    - test-workspace
    - test-bzlmod
    steps:
    - run: |
        if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled"
            exit 1
        fi
        echo "All required jobs passed or were skipped"
