name: Bazel CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}


jobs:
  request:
    runs-on: ubuntu-24.04
    outputs:
      run: ${{ steps.filter.outputs.run }}
    steps:
    - uses: envoyproxy/toolshed/actions/github/should-run@808a57c88b4cbf2560d3aa067b030e87c24306c8
      id: filter
      with:
        config: |
          paths:
          - BINS_VERSION.txt
          - bazel/**
          - .github/workflows/bazel.yml
          - .github/workflows/_bazel.yml

  test:
    needs: request
    if: >-
      always()
      && fromJSON(needs.request.outputs.run || 'false')
    uses: ./.github/workflows/_bazel.yml
    with:
      action: test
      bazel-args: >-
        --config=ci
        ${{ matrix.mode == 'bzlmod'
            && '--enable_bzlmod'
            || '' }}
      bazel-mode: ${{ matrix.mode }}
      bazel-path: bazel
      targets: >-
        //...
        //sysroot:sysroots
    strategy:
      fail-fast: false
      matrix:
        mode:
        - workspace
        - bzlmod

  build:
    permissions:
      contents: write
    needs: request
    if: >-
      always()
      && fromJSON(needs.request.outputs.run || 'false')
    uses: ./.github/workflows/_bazel.yml
    with:
      action: build
      artifacts: |
          compile/msan-llvm18.1.8-x86_64.tar.xz
          compile/tsan-llvm18.1.8-x86_64.tar.xz
          sysroot/sysroot-*.tar.xz
      bazel-args: >-
        --config=ci
        ${{ matrix.mode == 'bzlmod'
            && '--enable_bzlmod'
            || '' }}
      bazel-path: bazel
      bazel-mode: ${{ matrix.mode }}
      targets: >-
        //...
        //sysroot:sysroots
      upload: ${{ matrix.mode == 'workspace' }}
    strategy:
      fail-fast: false
      matrix:
        mode:
        - workspace
        - bzlmod

  status:
    runs-on: ubuntu-24.04
    if: >-
      always()
      && github.event_name == 'pull_request'
    name: Bazel
    needs:
    - request
    - test
    - build
    steps:
    - run: |
        if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled"
            exit 1
        fi
        echo "All required jobs passed or were skipped"
