name: Publishing CI

permissions:
  actions: read

on:
  pull_request:
    paths:
    - .github/workflows/_publish.yml
    - .github/workflows/publishing.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  should:
    runs-on: ubuntu-24.04
    outputs:
      run: ${{ steps.filter.outputs.run }}
    steps:
    - uses: envoyproxy/toolshed/gh-actions/github/should-run@b78171200b6cf28afef2fd16c9015e8dba6e37cc
      id: filter
      with:
        config: |
          paths:
          - '.github/workflows/_publish.yml'
          - '.github/workflows/publishing.yml'

  get-main:
    runs-on: ubuntu-24.04
    needs: should
    if: fromJSON(needs.should.outputs.run || 'false')
    outputs:
      message: ${{ steps.commit.outputs.message }}
      sha: ${{ steps.commit.outputs.sha }}
    steps:
    - name: Get latest commit from main
      id: commit
      env:
        GH_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
      run: |
        SHA=$(gh api /repos/${{ 'envoyproxy/toolshed' || github.repository }}/git/ref/heads/main --jq '.object.sha')
        echo "sha=$SHA" >> $GITHUB_OUTPUT
        echo "Latest SHA from main: $SHA"
        MESSAGE=$(\
            gh api "/repos/${REPO}/commits/${SHA}" \
                --jq '.commit.message | split("\n") | first')
        echo "message=$MESSAGE" >> $GITHUB_OUTPUT
        echo "Latest MESSAGE from main: $MESSAGE"

  publish:
    needs:
    - should
    - get-main
    if: fromJSON(needs.should.outputs.run || 'false')
    permissions:
      actions: read
    uses: ./.github/workflows/_publish.yml
    with:
      commit-message: ${{ needs.get-main.outputs.message }}
      conclusion: ${{ matrix.conclusion || 'success' }}
      bins-version: ${{ matrix.bins-version }}
      dry-run: true
      event: ${{ matrix.event }}
      python-version: ${{ matrix.python-version }}
      sha: ${{ matrix.sha || needs.get-main.outputs.sha }}
      skip: ${{ matrix.skip || (github.event_name != 'pull_request' && matrix.event == 'pull_request') }}
      workflows: |
        Bazel CI
        Python CI
        Rust CI
    strategy:
      fail-fast: false
      matrix:
        include:
        - sha: ${{ github.event.pull_request.head.sha }}
          event: pull_request
        - event: push
        - event: push
          bins-version: 0.1.23
        - event: push
          python-version: 0.0.23
        - event: push
          bins-version: 0.1.23
          python-version: 0.0.23
        - event: push
          conclusion: failure
        - event: push
          skip: true

  status:
    runs-on: ubuntu-24.04
    if: >-
      always()
      && github.event_name == 'pull_request'
    name: Publishing
    needs:
    - should
    - get-main
    - publish
    steps:
    - run: |
        if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled"
            exit 1
        fi
        echo "All required jobs passed or were skipped"
