name: Publishing CI

permissions:
  actions: read

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  request:
    runs-on: ubuntu-24.04
    outputs:
      message: ${{ steps.commit.outputs.message }}
      run: ${{ steps.filter.outputs.run }}
      sha: ${{ steps.commit.outputs.sha }}
    steps:
    - uses: envoyproxy/toolshed/actions/github/should-run@7a402831161ab6c666b7db906b0e5f5d07fd38fe
      id: filter
      with:
        config: |
          paths:
          - .github/workflows/_publish.yml
          - .github/workflows/_publish_release.yml
          - .github/workflows/actions.yml
          - .github/workflows/bazel.yml
          - .github/workflows/rust.yml
          - .github/workflows/publishing.yml
          - bazel/VERSION.txt
          - BINS_VERSION.txt
          - actions/VERSION.txt
          - python/VERSION.txt
    - name: Get latest commit from main
      id: commit
      if: fromJSON(steps.filter.outputs.run)
      env:
        GH_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
      run: |
        SHA=$(gh api /repos/${{ 'envoyproxy/toolshed' || github.repository }}/git/ref/heads/main --jq '.object.sha')
        echo "sha=$SHA" >> $GITHUB_OUTPUT
        echo "Latest SHA from main: $SHA"
        MESSAGE=$(\
            gh api "/repos/${REPO}/commits/${SHA}" \
                --jq '.commit.message | split("\n") | first')
        echo "message=$MESSAGE" >> $GITHUB_OUTPUT
        echo "Latest MESSAGE from main: $MESSAGE"

  publish:
    needs:
    - request
    if: fromJSON(needs.request.outputs.run || 'false')
    permissions:
      actions: read
    # secrets.ENVOY_GPG_SNAKEOIL_KEY_PASSWORD
    # secrets.ENVOY_GPG_SNAKEOIL_KEY
    uses: ./.github/workflows/_publish.yml
    with:
      committer-email: "140627008+publish-envoy[bot]@users. noreply.github.com"
      committer-name: "publish-envoy[bot]"
      conclusion: ${{ matrix.conclusion || 'success' }}
      actions-version: ${{ matrix.actions-version }}
      bazel-version: ${{ matrix.bazel-version }}
      bins-version: ${{ matrix.bins-version }}
      dry-run: true
      event: ${{ matrix.event }}
      python-filter-artifacts: ${{ matrix.python-filter-artifacts }}
      python-version: ${{ matrix.python-version }}
      sha: ${{ matrix.sha || needs.request.outputs.sha }}
      skip: ${{ matrix.skip || (github.event_name != 'pull_request' && matrix.event == 'pull_request') }}
      title: ${{ needs.request.outputs.message }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - sha: ${{ github.event.pull_request.head.sha }}
          event: pull_request
        - event: push
        - event: push
          actions-version: 0.0.123
        - event: push
          bazel-version: 0.2.17
        - event: push
          bins-version: 0.1.23
        - event: push
          python-version: 0.0.23
        - event: push
          python-version: 0.0.23
          python-filter-artifacts: .
        - event: push
          actions-version: 0.0.123
          bazel-version: 0.2.17
          bins-version: 0.1.23
          python-version: 0.0.23
        # existing versions
        - event: push
          actions-version: 0.3.33
          bazel-version: 0.3.11
          bins-version: 0.1.27
          # not pre-existing version
          python-version: 0.0.23
        - event: push
          conclusion: failure
        - event: push
          skip: true

  status:
    runs-on: ubuntu-24.04
    if: >-
      always()
      && github.event_name == 'pull_request'
    name: Publishing
    needs:
    - request
    - publish
    steps:
    - run: |
        if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled"
            exit 1
        fi
        echo "All required jobs passed or were skipped"
