name: Release

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      type:
        description: Release type
        required: true
        type: choice
        options:
        - actions
        - bins
        - bazel
        - python
      action:
        type: choice
        options:
        - release
        - prepare
        - release-no-prepare
      dry-run:
        description: Dry run (no PR created).
        type: boolean
        default: false
      prepare-args:
        description: Prepare args.
        type: string
        default:


jobs:
  bump-version:
    secrets:
      app-id: ${{ ! inputs.dry-run && secrets.ENVOY_CI_PUBLISH_APP_ID }}
      app-key: ${{ ! inputs.dry-run && secrets.ENVOY_CI_PUBLISH_APP_KEY }}
    uses: ./.github/workflows/_release.yml
    with:
      action: ${{ inputs.action }}
      committer-name: publish-envoy[bot]
      committer-email: 140627008+publish-envoy[bot]@users.noreply.github.com
      dry-run: ${{ inputs.dry-run }}
      prepare-args: ${{ inputs.prepare-args }}
      type: ${{ inputs.type }}
