name: Releasing CI

permissions:
  actions: read

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  request:
    runs-on: ubuntu-24.04
    outputs:
      message: ${{ steps.commit.outputs.message }}
      run: ${{ steps.filter.outputs.run }}
      sha: ${{ steps.commit.outputs.sha }}
    steps:
    - uses: envoyproxy/toolshed/actions/github/should-run@a64caca35cf1872601518b84aa85650c06ef85e2
      id: filter
      with:
        config: |
          paths:
          - .github/workflows/_release.yml
          - .github/workflows/actions.yml
          - .github/workflows/bazel.yml
          - .github/workflows/rust.yml
          - .github/workflows/releasing.yml
          - bazel/VERSION.txt
          - BINS_VERSION.txt
          - actions/VERSION.txt
          - python/VERSION.txt
    - name: Get latest commit from main
      id: commit
      if: fromJSON(steps.filter.outputs.run)
      env:
        GH_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
      run: |
        SHA=$(gh api /repos/${{ 'envoyproxy/toolshed' || github.repository }}/git/ref/heads/main --jq '.object.sha')
        echo "sha=$SHA" >> $GITHUB_OUTPUT
        echo "Latest SHA from main: $SHA"
        MESSAGE=$(\
            gh api "/repos/${REPO}/commits/${SHA}" \
                --jq '.commit.message | split("\n") | first')
        echo "message=$MESSAGE" >> $GITHUB_OUTPUT
        echo "Latest MESSAGE from main: $MESSAGE"

  release:
    needs:
    - request
    if: fromJSON(needs.request.outputs.run || 'false')
    permissions:
      contents: read
    uses: ./.github/workflows/_release.yml
    with:
      committer-name: CI TESTING
      committer-email: ci-testing@does.not.exist
      dry-run: true
      action: ${{ matrix.action }}
      prepare-args: >-
        ${{ matrix.type == 'python-args'
            && '-u abstracts -u aio.api.github -u envoy.base.utils=0.6.0'
            || '' }}
      release-version: >-
        ${{ matrix.type == 'actions-with-version'
            && '0.3.99'
            || '' }}
      type: >-
        ${{
          matrix.type == 'python-args' && 'python'
          || matrix.type == 'actions-with-version' && 'actions'
          || matrix.type
        }}
      warn-on-error: ${{ matrix.type == 'python' && true || false }}
    strategy:
      fail-fast: false
      matrix:
        type:
        - actions
        - actions-with-version
        - bazel
        - bins
        - python
        - python-args
        action:
        - prepare
        - release

  status:
    runs-on: ubuntu-24.04
    if: >-
      always()
      && github.event_name == 'pull_request'
    name: Publishing
    needs:
    - request
    - release
    steps:
    - run: |
        if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled"
            exit 1
        fi
        echo "All required jobs passed or were skipped"
