name: Release

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run (no PR created).
        type: boolean
        default: false
      prepare:
        description: Run any preparatory steps.
        type: boolean
        default: true
      prepare-only:
        description: |
          Only run the preparatory steps (ie don't update the version).
        type: boolean
        default: true
      type:
        description: Release type
        required: true
        type: choice
        options:
        - actions
        - bins
        - bazel
        - python


jobs:
  bump-version:
    secrets:
      app-id: ${{ ! inputs.dry-run && secrets.ENVOY_CI_PUBLISH_APP_ID }}
      app-key: ${{ ! inputs.dry-run && secrets.ENVOY_CI_PUBLISH_APP_KEY }}
    uses: ./.github/workflows/_release.yml
    with:
      committer-name: publish-envoy[bot]
      committer-email: 140627008+publish-envoy[bot]@users.noreply.github.com
      dry-run: ${{ inputs.dry-run }}
      prepare: ${{ inputs.prepare }}
      prepare-only: ${{ inputs.prepare-only }}

      type: ${{ inputs.type }}
