name: Releasing CI

permissions:
  actions: read

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  request:
    runs-on: ubuntu-24.04
    outputs:
      message: ${{ steps.commit.outputs.message }}
      run: ${{ steps.filter.outputs.run }}
      sha: ${{ steps.commit.outputs.sha }}
    steps:
    - uses: envoyproxy/toolshed/gh-actions/github/should-run@368bc1188c06426fe419d10e76c95b3ce2ef565b
      id: filter
      with:
        config: |
          paths:
          - .github/workflows/_release.yml
          - .github/workflows/actions.yml
          - .github/workflows/bazel.yml
          - .github/workflows/rust.yml
          - .github/workflows/releasing.yml
          - bazel/VERSION.txt
          - BINS_VERSION.txt
          - gh-actions/VERSION.txt
          - python/VERSION.txt
    - name: Get latest commit from main
      id: commit
      if: fromJSON(steps.filter.outputs.run)
      env:
        GH_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
      run: |
        SHA=$(gh api /repos/${{ 'envoyproxy/toolshed' || github.repository }}/git/ref/heads/main --jq '.object.sha')
        echo "sha=$SHA" >> $GITHUB_OUTPUT
        echo "Latest SHA from main: $SHA"
        MESSAGE=$(\
            gh api "/repos/${REPO}/commits/${SHA}" \
                --jq '.commit.message | split("\n") | first')
        echo "message=$MESSAGE" >> $GITHUB_OUTPUT
        echo "Latest MESSAGE from main: $MESSAGE"

  release:
    needs:
    - request
    if: fromJSON(needs.request.outputs.run || 'false')
    permissions:
      contents: read
    uses: ./.github/workflows/_release.yml
    with:
      committer-name: CI TESTING
      committer-email: ci-testing@does.not.exist
      dry-run: true
      action: ${{ matrix.action }}
      type: ${{ matrix.type }}
    strategy:
      fail-fast: false
      matrix:
        type:
        - actions
        - bazel
        - bins
        - python
        action:
        - prepare
        - release

  status:
    runs-on: ubuntu-24.04
    if: >-
      always()
      && github.event_name == 'pull_request'
    name: Publishing
    needs:
    - request
    - release
    steps:
    - run: |
        if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled"
            exit 1
        fi
        echo "All required jobs passed or were skipped"
